// #pragma once
// #include <stdint.h>
// #include <stddef.h>
// #include <stdbool.h>
// #include <limine.h>//not sure if i actually need to include so many .h files
// #include <flanterm/flanterm.h>
// #include <flanterm/backends/fb.h>

// static inline uint8_t inb(uint16_t port);//chatgpt generated. try to rewrite in the future if possible


// static uint8_t get_key();//chatgpt generated. try to rewrite in the future if possible

// static uint8_t get_kb_status();

// static void scancode_to_string(uint8_t scancode, char* str);


// static const char scanmap_set1[128] = {//generated by chatgpt
//     0,   0,   '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '\b',   '\t', // 0x00 - 0x0F//0x0e is backspace
//     'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\n', 0,   'a', 's', // 0x10 - 0x1F
//     'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\'', '`', 0,   '\\', 'z', 'x', 'c', 'v', // 0x20 - 0x2F
//     'b', 'n', 'm', ',', '.', '/', 0,   '*', 0,   ' ', 0,   0,   0,   0,   0,   0,   // 0x30 - 0x3F
//     0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   // 0x40 - 0x4F
//     0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   // 0x50 - 0x5F
//     0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0    // 0x60 - 0x6F
// };

// static const char scanmap_set1_upper[128] = {//generated by chatgpt
//     0,   0,   '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '\b',   '\t',
//     'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '\n', 0,   'A', 'S',
//     'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '"', '~', 0,   '|', 'Z', 'X', 'C', 'V',
//     'B', 'N', 'M', '<', '>', '?', 0,   '*', 0,   ' ', 0,   0,   0,   0,   0,   0,
//     0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0
// };

// static bool is_lshift();

// void poll_kb(struct flanterm_context* ft_ctx);