#include <kutils.h>

//kprint() is defined in main.c

void bp(void) {
}
#include <stdint.h>

void uint64_to_string(uint64_t value, char* buffer) {//generated by chatgpt. there may be bugs
    // Start at the end of the buffer and build the string backward
    char* ptr = buffer;
    char* start = buffer;

    // Handle the case where the value is zero
    if (value == 0) {
        *ptr++ = '0';
    }
    else {
        // Extract digits and append them in reverse order
        while (value > 0) {
            *ptr++ = '0' + (value % 10); // Add '0' to convert digit to character
            value /= 10;
        }
    }

    *ptr = '\0'; // Null-terminate the string

    // Reverse the string in place
    char* end = ptr - 1;
    while (start < end) {
        char temp = *start;
        *start++ = *end;
        *end-- = temp;
    }
}

void kprintln_uint64_to_binary(uint64_t value) {//generated by chatgpt. there may be bugs
    for (int i = 63; i >= 0; i--) {
        if (value & (1ULL << i)) {
            kprint("1");
        }
        else {
            kprint("0");
        }

        if (i % 8 == 0 && i != 0) {  // Add space every 8 bits for readability
            kprint(" ");
        }
    }
    kprint("\n");
}

void kprint_char(char c) {
    char s[2];
    s[0] = c;
    s[1] = '\0';
    kprint(s);
}


//taken straight from mishakov
uint64_t read_flags() {
    uint64_t flags;
    asm volatile ("pushf ; pop %0" : "=ro"(flags) :: "memory");
    return flags;
}
  
void irq_disable_save(bool *old_value) {
    if (old_value) *old_value = read_flags() & (1 << 9); 
    asm volatile ("cli");
}

void irq_restore(bool *status) {
    if (!status || *status) asm volatile ("sti");
}



//these are all just taken from keyboard.c but slightly changed

const char scanmap_set1[128] = {//generated by chatgpt
    0,   0,   '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '\b',   '\t', // 0x00 - 0x0F//0x0e is backspace
    'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\n', 0,   'a', 's', // 0x10 - 0x1F
    'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\'', '`', 0,   '\\', 'z', 'x', 'c', 'v', // 0x20 - 0x2F
    'b', 'n', 'm', ',', '.', '/', 0,   '*', 0,   ' ', 0,   0,   0,   0,   0,   0,   // 0x30 - 0x3F
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   // 0x40 - 0x4F
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   // 0x50 - 0x5F
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0    // 0x60 - 0x6F
};

const char scanmap_set1_upper[128] = {//generated by chatgpt
    0,   0,   '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '\b',   '\t',
    'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '\n', 0,   'A', 'S',
    'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '"', '~', 0,   '|', 'Z', 'X', 'C', 'V',
    'B', 'N', 'M', '<', '>', '?', 0,   '*', 0,   ' ', 0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0
};

char* scancode_to_string(uint8_t scancode) {
    //since the uint8_t scancode can be represented in binary, we just shift it and mask part of it to grab the 4 bits we want
    char h[] = "0123456789abcdef";
    char str[4];
    str[0] = '0';
    str[1] = 'x';
    str[2] = h[(scancode >> 4)];//high nibble
    //str[3] = h[(scancode << 4) >> 4];//low nibble//still not exactly sure why this line causes the low nibble to get dropped
    str[3] = h[(scancode & 0x0f)];//low nibble
    str[4] = '\0';
}

uint8_t get_key() {//chatgpt generated. try to rewrite in the future if possible
    uint8_t scan_code = inb(0x60); // Read from the keyboard's data port
    return scan_code;
}

uint8_t get_kb_status() {
    uint8_t status = inb(0x64);
    return status;
}



bool lshift_status = 0;

bool is_lshift(uint8_t scancode) {//may be a better idea to remove get_key() from here and just pass in the key directly idk
    uint8_t shift_pressed = 0x2a;
    uint8_t shift_released = 0xaa;
    if (scancode == shift_released) {//state != shift_pressed || 
        lshift_status = 0;
        return 0;
    }
    else if (scancode == shift_pressed) {//state != shift_released || 
        lshift_status = 1;
        return 1;
    }
}

uint8_t prev_key;
uint8_t mode = 0;

void print_kb(uint8_t scancode) {//not sure if this should be static. has a quirk where left shift is detected as pressed when the kernel first runs and it only gets reset when you press left shift
    uint8_t key = scancode;
    if (key == 0x2a || key == 0xaa || key >= 0x80) {
        return;
    }
    char c[2];
    c[1] = '\0';//doesn't seem right to just have to convert a char to a string this way
    if (lshift_status == 1) {
        c[0] = scanmap_set1_upper[key];
    }
    else if (lshift_status == 0) {
        c[0] = scanmap_set1[key];
    }
    if (c[0] == '\b') {//if it's backspace
        kprintf("\b \b");//not sure if it should be interruptable or not here
    }
    else {
        kprintf("%c", c[0]);
    }
}

char* strncpy(char* s1, char* s2, size_t n) {//taken straight from glibc
    size_t size = kstrlen(s2);//not sure if it handles something without null terminating char
    if (size != n)
      memset(s1 + size, '\0', n - size);
    return memcpy (s1, s2, size);
}

int strcmp (const char *p1, const char *p2) {//taken straight from glibc
  const unsigned char *s1 = (const unsigned char *) p1;
  const unsigned char *s2 = (const unsigned char *) p2;
  unsigned c1, c2;

  do
    {
      c1 = (unsigned char) *s1++;
      c2 = (unsigned char) *s2++;
      if (c1 == '\0')
	return c1 - c2;
    }
  while (c1 == c2);

  return c1 - c2;
}

//taken from libc
char* strtok(char *s, const char *delim)
{
	static char *last;
	return strtok_r(s, delim, &last);
}
char* strtok_r(char *s, const char *delim, char **last)
{
	char *spanp;
	int c, sc;
	char *tok;
	if (s == NULL && (s = *last) == NULL)
		return (NULL);
	/*
	 * Skip (span) leading delimiters (s += strspn(s, delim), sort of).
	 */
cont:
	c = *s++;
	for (spanp = (char *)delim; (sc = *spanp++) != 0;) {
		if (c == sc)
			goto cont;
	}
	if (c == 0) {		/* no non-delimiter characters */
		*last = NULL;
		return (NULL);
	}
	tok = s - 1;
	/*
	 * Scan token (scan for delimiters: s += strcspn(s, delim), sort of).
	 * Note that delim must have one NUL; we stop if we see that, too.
	 */
	for (;;) {
		c = *s++;
		spanp = (char *)delim;
		do {
			if ((sc = *spanp++) == c) {
				if (c == 0)
					s = NULL;
				else
					s[-1] = 0;
				*last = s;
				return (tok);
			}
		} while (sc != 0);
	}
	/* NOTREACHED */
}


//from osdev wiki on ustar
//https://wiki.osdev.org/USTAR
int oct2bin(unsigned char *str, int size) {
    int n = 0;
    unsigned char *c = str;
    while (size-- > 0) {
        n *= 8;
        n += *c - '0';
        c++;
    }
    return n;
}

/* returns file size and pointer to file data in out */
int tar_lookup(unsigned char *archive, char *filename, char **out) {
    unsigned char *ptr = archive;

    while (!memcmp(ptr + 257, "ustar", 5)) {
        int filesize = oct2bin(ptr + 0x7c, 11);
        if (!memcmp(ptr, filename, kstrlen(filename) + 1)) {
            *out = ptr + 512;
            return filesize;
        }
        ptr += (((filesize + 511) / 512) + 1) * 512;
    }
    return 0;
}



/* itoa:  convert n to characters in s */
void itoa(int n, char s[])
{
    int i, sign;

    if ((sign = n) < 0)  /* record sign */
        n = -n;          /* make n positive */
    i = 0;
    do {       /* generate digits in reverse order */
        s[i++] = n % 10 + '0';   /* get next digit */
    } while ((n /= 10) > 0);     /* delete it */
    if (sign < 0)
        s[i++] = '-';
    s[i] = '\0';
    itoa_reverse(s);
}

/* reverse:  reverse string s in place */
void itoa_reverse(char s[])
{
    int i, j;
    char c;

    for (i = 0, j = kstrlen(s)-1; i<j; i++, j--) {
        c = s[i];
        s[i] = s[j];
        s[j] = c;
    }
}


uint64_t tar_lookup_bin(char* tarball, char* filename, char** file_data) {//currently no protection against trying to find a file that doens't exist
    uint64_t a_size = tar_lookup(tarball, filename, file_data);

    char a_str[13];          // 12 digits + null terminator
    a_str[12] = '\0';        // Null-terminate
    
    for (int j = 11; j >= 0; j--) {//chatgpt generated
        a_str[j] = '0' + (a_size % 10);
        a_size /= 10;
    }
    uint64_t b_size = oct2bin(a_str, 12);
    b_size++;//idk why but b_size seems to be one less than the actual size

    return b_size;//HERE B_SIZE HAS BEEN INCREMENTED BY ONE
}

//stolen from nyaux
uint64_t rdmsr(uint32_t msr) {
  uint32_t low = 0;
  uint32_t high = 0;
  __asm__ volatile("rdmsr" : "=a"(low), "=d"(high) : "c"(msr));
  uint64_t combined = ((uint64_t)high << 32) | low;
  return combined;
}
void wrmsr(uint32_t msr, uint64_t value) {
  uint32_t low = (uint32_t)value;
  uint32_t high = (uint32_t)(value >> 32);
  __asm__ volatile("wrmsr" : : "a"(low), "d"(high), "c"(msr));
}