#include <kutils.h>

//kprint() is defined in main.c

void bp(void) {
}
#include <stdint.h>

void uint64_to_string(uint64_t value, char* buffer) {//generated by chatgpt. there may be bugs
    // Start at the end of the buffer and build the string backward
    char* ptr = buffer;
    char* start = buffer;

    // Handle the case where the value is zero
    if (value == 0) {
        *ptr++ = '0';
    }
    else {
        // Extract digits and append them in reverse order
        while (value > 0) {
            *ptr++ = '0' + (value % 10); // Add '0' to convert digit to character
            value /= 10;
        }
    }

    *ptr = '\0'; // Null-terminate the string

    // Reverse the string in place
    char* end = ptr - 1;
    while (start < end) {
        char temp = *start;
        *start++ = *end;
        *end-- = temp;
    }
}
