#include <kutils.h>

//kprint() is defined in main.c

void bp(void) {
}
#include <stdint.h>

void uint64_to_string(uint64_t value, char* buffer) {//generated by chatgpt. there may be bugs
    // Start at the end of the buffer and build the string backward
    char* ptr = buffer;
    char* start = buffer;

    // Handle the case where the value is zero
    if (value == 0) {
        *ptr++ = '0';
    }
    else {
        // Extract digits and append them in reverse order
        while (value > 0) {
            *ptr++ = '0' + (value % 10); // Add '0' to convert digit to character
            value /= 10;
        }
    }

    *ptr = '\0'; // Null-terminate the string

    // Reverse the string in place
    char* end = ptr - 1;
    while (start < end) {
        char temp = *start;
        *start++ = *end;
        *end-- = temp;
    }
}

void kprintln_uint64_to_binary(uint64_t value) {//generated by chatgpt. there may be bugs
    for (int i = 63; i >= 0; i--) {
        if (value & (1ULL << i)) {
            kprint("1");
        }
        else {
            kprint("0");
        }

        if (i % 8 == 0 && i != 0) {  // Add space every 8 bits for readability
            kprint(" ");
        }
    }
    kprint("\n");
}

void kprint_char(char c) {
    char s[2];
    s[0] = c;
    s[1] = '\0';
    kprint(s);
}


//taken straight from mishakov
uint64_t read_flags() {
    uint64_t flags;
    asm volatile ("pushf ; pop %0" : "=ro"(flags) :: "memory");
    return flags;
}
  
void irq_disable_save(bool *old_value) {
    if (old_value) *old_value = read_flags() & (1 << 9); 
    asm volatile ("cli");
}

void irq_restore(bool *status) {
    if (!status || *status) asm volatile ("sti");
}