#ifndef _MLIBC_CONFIG_H
#define _MLIBC_CONFIG_H

#define __MLIBC_BSD_OPTION 0
#define __MLIBC_POSIX_OPTION 0
#define __MLIBC_LINUX_OPTION 0
#define __MLIBC_GLIBC_OPTION 0
#define __MLIBC_SYSDEP_HAS_BITS_SYSCALL_H 0

#endif /* _MLIBC_CONFIG_H */
